### ISSUE TITLE
Device reboots as soon as HMA is opened

### ISSUE THREAD

**Issue by amritpal2489** [adrianmmiller/Hide-My-Applist-Guide#3]
My Pixel 6 Pro running UPB1 230309.014 build reboots as soon as HMA latest version is opened.

**Comment by adrianmmiller** [comment]
I dont have UPB1, and you would seemingly be the 1st to try it on that beta of Android

As its beta, and HMA's author hasnt tested or updated it for that, this isnt something i can fix, and your choices should be obvious, either dont use it, or revert to stable version of Android. Sorry

This issue is therefore taken as informative
